
				// Code generated by hero.
			// source: C:\Users\apple\go\src\miniblog\template\reset_password.html
				// DO NOT EDIT!
			package template

				import "html"
				import "unsafe"

				import "github.com/shiyanhui/hero"
			